### ISSUE TITLE
[UpdatePlugin]  whitequark binja_itanium_cxx_abi v1.1

### ISSUE THREAD

**Issue by whitequark** [Vector35/community-plugins#107]
Please update my plugin:

Author: Me
Repo name: whitequark/binja_itanium_cxx_abi
Release: v1.1

**Comment by psifertex** [comment]
Thanks! Added. Bah, sorry, I had this comment written and not submitted back when I did this two days ago. I know I already let you know via slack.  :-) 

If I could request on the next release, can you please use "1.2" instead of "v1.2"? We're trying to normalize not having "v" in the version. We realize /we/ set a bad example with our blog and original plugins but we're trying to clean them up now. :-)

**Comment by whitequark** [comment]
> If I could request on the next release, can you please use "1.2" instead of "v1.2"?

For the tag name? But tags are used for things other than versions, so I don't like this proposal.

**Comment by psifertex** [comment]
Actually, I just realized you did indeed have the version field of the plugin.json already with "1.1" which is the main area where normalization matters so the exact tag doesn't matter so much.

Originally I was thinking we'd standardize just to prevent confusion/differences between the two but the more I think about it now, the more I'm wondering about the best way to handle the auto-incrementing if our cronjob that we were discussion in slack would detect updates. I guess all that it has to do is check that the currently released tag is not the same as the one stored in our config file and update it so. If that's the case, then the exact tag doesn't matter at all.

**Comment by whitequark** [comment]
Yep.
