### ISSUE TITLE
[NewPlugin] Opaque Predicates Detective @v0.1

### ISSUE THREAD

**Issue by yellowbyte** [Vector35/community-plugins#166]
Author: Yu-Jye Tung
Link To Repo: https://github.com/yellowbyte/opaque-predicates-detective
Tag Name: v0.1

Thanks!

**Comment by psifertex** [comment]
Great! Glad to see the plugin is ready for the plugin manager! We also have the analysis pass API in development and I'm excited to see how plugins such as this could take advantage of that as it is hopefully available soon. 

I'll be able to add this plugin tomorrow or first thing next week. One thing I'd request first though is: can you do a new release without the long description entirely in the plugin.json? I've recently updated the channel generator so that it will fall back to using the existing readme.md contents which would work much better for this plugin as opposed to converting the readme contents into the plugin.json file. 

Additionally, you might want to remove the mention in the readme that the plugin isn't available via the plugin manager since it will be shortly! :-) 

Thanks again foe the submission.

**Comment by yellowbyte** [comment]
I will for sure be on the lookout for the analysis pass API release! And yes, I will do a new release with the changes. Also, thanks for catching my readme blunder; happy to know that someone read my readme!

**Comment by psifertex** [comment]
No worries, I always like to check it for new plugins since I want them to have a nice looking readme show up when they are in the plugin manager. :-) 

Also, the previous process was a bit onerous on plugin maintainers having to have the same content in both so just being able to use the readme is much easier. Go ahead and just update this issue when you've got a new release and I'll add it.

**Comment by yellowbyte** [comment]
Just updated! tag name is still "v0.1". I deleted the long description field from plugin.json (let me know if that's not what you meant). 

Thanks again!

**Comment by psifertex** [comment]
Added, thanks! (I got out of bed just to check the plugin out more instead of just reading on my phone. 😉 )
