### ISSUE TITLE
[NewPlugin]  lockbox pd-ninja 1.0

### ISSUE THREAD

**Issue by lockbox** [Vector35/community-plugins#207]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: Me
Repo name: [pd-ninja](https://github.com/lockbox/pd-ninja)
Release: https://github.com/lockbox/pd-ninja/releases/tag/1.2

**Comment by psifertex** [comment]
Ouch -- very sorry for the delay in responding here. Not sure how I missed this one. Do you mind adding a `requirements.txt` with the [dependencies](https://github.com/lockbox/pd-ninja#required-dependencies) described in the readme so that the plugin manager can automatically install them? That will make it significantly easier for folks to use.

**Comment by lockbox** [comment]
done in lockbox/pd-ninja#3

**Comment by psifertex** [comment]
Added to the plugin manager and looks like it installs though I don't have any samples to test on. Let me know if there's any trouble with it.
