### ISSUE TITLE
All of your license links 404

### ISSUE THREAD

**Issue by yrp604** [Vector35/community-plugins#25]
Obviously minor, but from the main big list, all the licenses 404.

For example, the Syscaller license is: https://github.com/Vector35/community-plugins/blob/master/plugins/Syscaller/LICENSE

**Comment by psifertex** [comment]
Yeah, it's a function of folks not using the same generator I did that creates the LICENSE and README files based on the plugin.json. :-/

Notice how it exists here: https://github.com/Vector35/sample_plugin and is created by https://github.com/Vector35/sample_plugin/blob/master/generate_readme.py#L16

I guess I could update the docs to encourage better behavior, or alternatively I could just link to the plugin.json since that field exists there as well, not sure the better course.

**Comment by yrp604** [comment]
Sure, it was more of an FYI issue as opposed to "you should definitely fix this". Feel free to close, I don't think anyone will lose sleep over it.

On the subject of that script, it doesn't gracefully handle licenses with utf8 characters. I've patched it here https://github.com/yrp604/sample_plugin/commit/a84b85adaac9b4f1a704d29db93a3db8174af19f and am happy to PR if you want, but it seemed like kinda a silly thing. Clearly I am adept at finding hard-hitting issues in BN's very core.

**Comment by psifertex** [comment]
I updated the sample plugin but still haven't gotten around to updating the main generator. I started to do that but disliked so much of the original implementation that I want to fix it in a better way and I'm going to hold off for a little bit. Keeping this open until I do that.

**Comment by psifertex** [comment]
Closing this out as the immediate issue was resolved and we have a separate refactor of the generator based on the new changes for the UI plugin that @plafosse is working on.
