### ISSUE TITLE
[New Plugin]: PowerPC VLE Extension

### ISSUE THREAD

**Issue by Martyx00** [Vector35/community-plugins#263]
### Plugin Description

Extends the default PPC architecture to add VLE instructions.

### Plugin Repository URL

Repo URL: https://github.com/Martyx00/PowerPC-VLE-Extension

### Real Release

- [X] I have made a real release

**Comment by Martyx00** [comment]
Since this is my first C++ plugin. How are these published/installed by the community? Will it grab the artifact from the runner or should I include manual instructions?

**Comment by psifertex** [comment]
Unfortunately we need some changes to the plugin manager before we can better support native plugins. I'm going to keep this open until then as we do plan to make some of those soon.

**Comment by psifertex** [comment]
Good news! We've added support for native plugins (still in view-only) mode. You can see an example plugin.json here:

https://github.com/unknowntrojan/binja_coolsigmaker/blob/master/plugin.json

In particular, you'll want to change your API to ["cpp"] instead of python3.

Note that in the plugin manager, the minimum version will be forced to be the current dev release as that's the only one that is supported from the UI with the new view-only type, but you can leave the true minimum version in the plugin.json if that's correct.

Once you've got that, let me know. I'll update you once we get better automation examples to track releases and automatically update (that's requiring some other changes coming with a new extension manager server infrastructure)

**Comment by Martyx00** [comment]
Hi, is there a quick and easy way to find the correct value for minimum required version? I always struggled with that.

**Comment by psifertex** [comment]
Well, 6135 is the version that supports view only plugins in plugin manager itself, so it's safe to just use that for now. 

For native plugins it's actually handled in the plugin itself and how it registers so it's not really an issue there.
Going forward hopefully the automation that tags and builds for a specific release will help. 

For python, one way is to just binary search the builds until you find the one that last worked correctly. Unfortunately I don't have anything much fancier than that.

**Comment by Martyx00** [comment]
Done :)

**Comment by psifertex** [comment]
Thanks! I've added it to the repo, when we make the second pass for actual automatic build tracking/updates we'll update the documentation and reach out to plugin authors directly so I'm closing this for now. Thanks for the plugin.
