### ISSUE TITLE
[New Plugin]: pDf Reference Opcodes Or reGisters (DROOG) 

### ISSUE THREAD

**Issue by amtal** [Vector35/community-plugins#270]
### Plugin Description

Per [the README's Usage section](https://github.com/amtal/droog?tab=readme-ov-file#usage), 

> This is a glorified PDF search for tokens that show up in tables of contents.
> 
> Select a token like an instruction or a register, and "Plugins" -> "DROOG" -> "Search Reference Headings..." will show pages from PDFs available for the current architecture. Click an image to open the PDF at that page in your browser.
> 
> For unfamiliar architectures, bind the search to a hotkey. There's also a command to peek at table of contents headings in the status bar for quickly reviewing mnemonics.

See repo README for a screenshot.

I added the `pymupdf` dependency as `"dependencies": "pymupdf>=1.19.0\n",` which I think is right but isn't in docs/testable? If it only works in `official` channel, I'll change it.

### Plugin Repository URL

Repo URL: https://github.com/amtal/droog

### Real Release

- [X] I have made a real release

**Comment by psifertex** [comment]
Dependencies are specified in requirements.txt (documented [here](https://docs.binary.ninja/dev/plugins.html#creating-the-plugin)). So you'll probably want to do a new release with that. It's actually a bug that the plugin.json dependencies field is overwritten by requirements.txt [during generation](https://github.com/Vector35/community-plugins/blob/master/generate_index.py#L151-L165) of the master list regardless of whether the json contains it as well. 

That particular bug is fixed in our new plugin/extension infrastructure which we'll be releasing soon.

**Comment by amtal** [comment]
Thank you for clear explanation. 1.0.1 minted to suit!

**Comment by psifertex** [comment]
Thanks! Updated.
