### ISSUE TITLE
[New Plugin]: Auto Enum

### ISSUE THREAD

**Issue by junron** [Vector35/community-plugins#287]
### Plugin Description

IDA/Binary Ninja Plugin to automatically identify and set enums for standard functions

### Plugin Repository URL

Repo URL: https://github.com/junron/auto-enum

### Real Release

- [X] I have made a real release

**Comment by psifertex** [comment]
Ignore that, the validator script doesn't know how to handle subdirectories.

**Comment by psifertex** [comment]
Sorry for the delay, finally got around to fixing an [unrelated issue](https://github.com/Vector35/community-plugins/commit/94d2a9749096240e41edf4ea27d35aebb8f9c581) and ran into the fact that the version string doesn't match. Please either use a release name like "0.1.0" instead of "v0.1.0", or change the field in the plugin.json to match. Preference toward removing the "v" but you can technically do either. Note you might also find this script helpful though I don't know if I've tested it on a subdirectory plugin before: 

https://github.com/Vector35/release_helper

**Comment by psifertex** [comment]
Thanks, added!
