### ISSUE TITLE
[plugin] jump-table-branch-editor

### ISSUE THREAD

**Issue by Vasco-jofra** [Vector35/community-plugins#39]
[_A plugin that eases fixing jump table branches_](https://github.com/Vasco-jofra/jump-table-branch-editor)

I made this plugin to help setting the branches of indirect jumps without having to use `set_user_indirect_branches` in the python console every time. (and because I also wanted to try the new UI stuff)

**Comment by psifertex** [comment]
Do you mind moving the included sample video and gif out of the repository onto something like YouTube? It seems rather wasteful to make the repo itself so much larger simply for those files since users will be cloning the repo to install it. 

Alternatively, maybe we need to add a field to the plugin.json that allows you to specify paths to exclude from the install in the interests of space?

**Comment by psifertex** [comment]
But thanks for the plugin! Glad to see the APIs getting some use.

**Comment by Vasco-jofra** [comment]
Fixed it! Not sure why the gif was almost 50MB. 

Now is < 1MB so I think it's fine. If you think I should still remove it, I'll host the gif somewhere else.

**Comment by shane-runsafe** [comment]
@Vasco-jofra from a repo perspective, you'll probably want to force push a new repo without the history, otherwise users will still end up cloning the large history (which in this case includes that 50MB gif and video).

**Comment by Vasco-jofra** [comment]
I remove'd it from the history as well I'm pretty sure. Just checked by cloning the repo and it's 1.7MB only

**Comment by psifertex** [comment]
Added this a while ago and forgot to close out.
