### ISSUE TITLE
[NewPlugin]  hugsy gef-binja 0.2

### ISSUE THREAD

**Issue by hugsy** [Vector35/community-plugins#94]
Please add my plugin to the repository.

Yes, I've read the instructions, especially the part about creating an [actual release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) and creating the tag. 

I either used the UI, or the `hub` command to create a _real_ release.

Author: hugsy
Repo name: [gef-binja](https://github.com/hugsy/gef-binja)
Release: [0.2](https://github.com/hugsy/gef-binja/releases/tag/v0.2)

PS: amazing work on the Plugin Manager (something that's been missing in IDA for way too long), and also for the HLIL.

**Comment by psifertex** [comment]
Thanks for the kind words! We have some future plans for the plugin manager as well to make it even more useful too.

One request: we are trying to standardize on versions as being "0.2" instead of "v0.2" -- initially even our examples and blog posts were mixing them which was an unfortunately mistake. Not a big deal and it works just fine as is so I'm adding the plugin now, but for future releases if you can have the tag just be "0.3" without the "v" that would be appreciated.

**Comment by hugsy** [comment]
Thanks for merging, and no problem I will stick to the "0.3" notation in the future!
